### ISSUE TITLE
bananopy.banano.NodeException: {'error': 'Internal server error. Could not reach node.'}

### ISSUE THREAD

**Issue by itsadityasai** [milkyklim/bananopy#28]
It's not a problem with my code.. Double checked using the example and this is what I got:

```
>>> import bananopy.banano as ban
Using https://api-beta.banano.cc as API provider on port 443
>>> ban.account_balance("ban_1bananobh5rat99qfgt1ptpieie5swmoth87thi74qgbfrij7dcgjiij94xr")
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    ban.account_balance("ban_1bananobh5rat99qfgt1ptpieie5swmoth87thi74qgbfrij7dcgjiij94xr")
  File "C:\Users\mateo\AppData\Roaming\Python\Python39\site-packages\bananopy\banano.py", line 27, in account_balance
    r = call("account_balance", payload)
  File "C:\Users\mateo\AppData\Roaming\Python\Python39\site-packages\bananopy\banano.py", line 20, in call
    raise NodeException(json_response)
bananopy.banano.NodeException: {'error': 'Internal server error. Could not reach node.'}
>>> 

```

What's going on?

**Comment by asaix** [comment]
I just ran an nmap scan to see if the port configuration changed but port 443 looks alright. 

```
Nmap scan report for api-beta.banano.cc (159.69.198.59)
Host is up (0.13s latency).
Other addresses for api-beta.banano.cc (not scanned): 2a01:4f8:c2c:5470::1
rDNS record for 159.69.198.59: static.59.198.69.159.clients.your-server.de
Not shown: 977 closed tcp ports (conn-refused)
PORT     STATE    SERVICE
22/tcp   open     ssh
25/tcp   filtered smtp
79/tcp   filtered finger
80/tcp   open     http
111/tcp  filtered rpcbind
113/tcp  filtered ident
135/tcp  filtered msrpc
139/tcp  filtered netbios-ssn
443/tcp  open     https
445/tcp  filtered microsoft-ds
512/tcp  filtered exec
513/tcp  filtered login
514/tcp  filtered shell
515/tcp  filtered printer
1025/tcp filtered NFS-or-IIS
1026/tcp filtered LSA-or-nterm
1063/tcp filtered kyoceranetdev
1080/tcp filtered socks
1434/tcp filtered ms-sql-m
3128/tcp filtered squid-http
4662/tcp filtered edonkey
6129/tcp filtered unknown
7070/tcp open     realserver

Nmap done: 1 IP address (1 host up) scanned in 11.17 seconds
```

**Comment by asaix** [comment]
Looks like it was just a problem with the node.. All fine now.
